import { Inter } from "next/font/google";
import "./globals.css";
import "@radix-ui/themes/styles.css";

export const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


